(()=>{
const $=id=>document.getElementById(id), money=n=>new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP',minimumFractionDigits:2,maximumFractionDigits:2}).format(Number.isFinite(n)?n:0), num=id=>Number($(id)?.value)||0;
document.querySelectorAll('.calc-tab').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.calc-tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.calc-panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('calc-'+b.dataset.target).classList.add('active')}));
let rows=[];
const math=window.CRMRateMath;
const rateChoices=[['apr_effective','APR'],['term_yield','Yield'],['factor','Factor rate'],['flat_monthly','Flat rate on original loan per month']];
const rateLabels={apr_effective:'APR (% effective annual rate, before fees)',term_yield:'Yield (% total interest over full term)',factor:'Factor multiple (e.g. 1.2)',flat_monthly:'Flat rate on original loan (% per month)'};
function inputs(prefix,amount,term,style='amortizing',frequency=12,balloon=0){return {amount,termMonths:term,style,frequency,balloon,rate:Math.max(0,num(prefix+'Rate')),mode:$(prefix+'Mode').value,fees:Math.max(0,num(prefix+'Fee'))*($(prefix+'FeeUnit').value==='percent'?amount/100:1),feeTreatment:$(prefix+'FeeTreatment').value,interestBasis:$(prefix+'Basis').value};}
function details(prefix,result){$(prefix+'TotalCost').textContent=money(result.totalCost);$(prefix+'Net').textContent=money(result.netAdvance);}
let loanResult;
function loan(){
 const freq=Number($('loanFrequency').value),raw=Math.max(1,Math.round(num('loanTerm'))),months=freq===4?Math.max(3,Math.round(raw/3)*3):raw;if(months!==raw)$('loanTerm').value=months;
 const input=inputs('loan',Math.max(0,num('loanAmount')),months,'amortizing',freq),result=math.calculate(input);loanResult=result;
 const flat=['flat_annual','flat_monthly','factor','term_yield'].includes(input.mode),rate=math.periodRate(input.rate,input.mode,freq)*(result.financedAmount?result.interestPrincipal/result.financedAmount:0);
 let balance=result.financedAmount;rows=[];
 for(let i=1;i<=result.periods;i++){const open=balance,interest=flat?result.financeCharge/result.periods:open*rate,capital=i===result.periods?open:Math.min(open,Math.max(0,result.payment-interest));balance=Math.max(0,open-capital);rows.push([i,open,capital+interest,interest,capital,balance]);}
 $('loanPayment').textContent=money(result.payment);$('loanInterest').textContent=money(result.financeCharge);$('loanTotal').textContent=money(result.totalRepayable);details('loan',result);
 $('scheduleBody').innerHTML=rows.map(r=>'<tr>'+r.map((v,i)=>'<td>'+(i?money(v):v)+'</td>').join('')+'</tr>').join('');
}
function io(){const input=inputs('io',Math.max(0,num('ioAmount')),Math.max(1,Math.round(num('ioTerm'))),$('ioType').value),result=math.calculate(input),display=math.interestOnlyMonthlyDisplay(input,result);$('ioMonthlyLabel').textContent=display.label;$('ioMonthly').textContent=money(display.value);$('ioInterest').textContent=money(result.financeCharge);$('ioCapital').textContent=money(result.financedAmount);$('ioTotalLabel').textContent='Total payable including fee';$('ioTotal').textContent=money(result.totalRepayable);details('io',result);$('ioNote').textContent='Amount due at maturity: '+money(result.balloon)+'. Retained interest reduces the net advance available; rolled-up interest is paid at maturity. Entered fees are included in total cost.';}
function dscr(){const cash=num('dscrEbitda')+num('dscrAdjust'),debt=Math.max(0,num('dscrExisting'))+Math.max(0,num('dscrProposed'));$('dscrCash').textContent=money(cash);$('dscrDebt').textContent=money(debt);$('dscrRatio').textContent=debt>0?(cash/debt).toFixed(2)+'x':'—'}
function asset(){const cost=Math.max(0,num('assetCost')),deposit=Math.min(cost,Math.max(0,num('assetDeposit'))),result=math.calculate(inputs('asset',cost-deposit,Math.max(1,Math.round(num('assetTerm'))),'amortizing',12,num('assetBalloon')));$('assetFinanced').textContent=money(result.financedAmount);$('assetPayment').textContent=money(result.payment);$('assetInterest').textContent=money(result.financeCharge);$('assetTotal').textContent=money(deposit+result.totalRepayable);details('asset',result);}
for(const [prefix,fn] of [['loan',loan],['io',io],['asset',asset]]){for(const suffix of ['Mode','Fee','FeeUnit','FeeTreatment','Basis'])$(prefix+suffix).addEventListener('input',fn);$(prefix+'Mode').innerHTML=rateChoices.map(([value,label])=>'<option value="'+value+'">'+label+'</option>').join('');$(prefix+'FeeUnit').addEventListener('input',()=>{$(prefix+'FeeLabel').textContent=$(prefix+'FeeUnit').value==='percent'?'Loan arrangement fee (% of loan amount)':'Loan arrangement fee (£)';});$(prefix+'Mode').value='apr_effective';const label=()=>{$(prefix+'RateLabel').textContent=rateLabels[$(prefix+'Mode').value];};$(prefix+'Mode').addEventListener('input',()=>{label();});label();}
[['loanAmount',loan],['loanRate',loan],['loanTerm',loan],['loanFrequency',loan],['ioAmount',io],['ioRate',io],['ioTerm',io],['ioType',io],['dscrEbitda',dscr],['dscrAdjust',dscr],['dscrExisting',dscr],['dscrProposed',dscr],['assetCost',asset],['assetDeposit',asset],['assetRate',asset],['assetTerm',asset],['assetBalloon',asset]].forEach(([id,fn])=>$(id)?.addEventListener('input',fn));

function pdfIllustration(){
 if(!rows.length)return;
 const amount=Math.max(0,num('loanAmount')), rate=Math.max(0,num('loanRate')), months=Math.max(1,Math.round(num('loanTerm'))), frequency=$('loanFrequency').options[$('loanFrequency').selectedIndex].text;
 const repayment=$('loanPayment').textContent,totalInterest=$('loanInterest').textContent,total=$('loanTotal').textContent,date=new Intl.DateTimeFormat('en-GB',{day:'2-digit',month:'long',year:'numeric'}).format(new Date());
 const table=rows.map(r=>'<tr>'+r.map((v,i)=>'<td>'+(i?v.toLocaleString('en-GB',{style:'currency',currency:'GBP'}):v)+'</td>').join('')+'</tr>').join('');
 const w=window.open('','_blank');
 if(!w){alert('Please allow pop-ups to create the PDF illustration.');return}
 w.document.write(`<!doctype html><html><head><title>ABF Finance Illustration</title><style>
 @page{size:A4;margin:15mm 14mm 17mm}*{box-sizing:border-box}body{font-family:Arial,sans-serif;color:#0B1F3B;margin:0;font-size:10px}.brand{border-bottom:3px solid #C9A96E;padding:0 0 14px;margin-bottom:22px;display:flex;justify-content:space-between;align-items:flex-end}.logo{font-family:Georgia,serif;font-size:23px;font-weight:bold;letter-spacing:.04em}.logo span{display:block;color:#C9A96E;font:700 7px Arial,sans-serif;letter-spacing:.22em;margin-top:5px}.date{color:#687386;font-size:9px}.title{font-family:Georgia,serif;font-size:25px;margin:0 0 7px}.intro{color:#687386;font-size:10px;margin-bottom:20px}.inputs,.results{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin-bottom:18px}.box{border:1px solid #d9dde3;padding:10px}.box label{display:block;color:#687386;font-size:8px;text-transform:uppercase;letter-spacing:.06em;margin-bottom:5px}.box strong{font-size:12px}.results .box{background:#0B1F3B;color:#fff;border-color:#0B1F3B}.results .box label{color:#dbe4ef}.results .box strong{color:#fff}.results{grid-template-columns:repeat(3,1fr)}h2{font-family:Georgia,serif;font-size:16px;margin:20px 0 9px}table{width:100%;border-collapse:collapse;font-size:8px}thead{display:table-header-group}th{background:#0B1F3B;color:white;padding:6px;text-align:right}th:first-child,td:first-child{text-align:center}td{padding:5px 6px;border-bottom:1px solid #e3e6ea;text-align:right}tr{page-break-inside:avoid}.disclaimer{margin-top:16px;padding-top:10px;border-top:1px solid #C9A96E;color:#687386;font-size:7.5px;line-height:1.45}.footer{margin-top:8px;font-size:7px;color:#8992a0;text-align:center}@media print{button{display:none}}
 </style></head><body><div class="brand"><div class="logo">ANYTIME BUSINESS FINANCE<span>EXPERIENCE. ACCESS. RESULTS.</span></div><div class="date">Finance Illustration · ${date}</div></div><h1 class="title">Loan Repayment & Amortisation Illustration</h1><p class="intro">Illustrative repayment schedule generated using the assumptions below.</p><div class="inputs"><div class="box"><label>Loan amount</label><strong>${money(amount)}</strong></div><div class="box"><label>Rate type / value</label><strong>${math.MODES.find(x=>x[0]===loanResult.mode)[1]}: ${rate}${loanResult.mode==='factor'?'':'%'}</strong></div><div class="box"><label>Term</label><strong>${months} months</strong></div><div class="box"><label>Frequency</label><strong>${frequency}</strong></div><div class="box"><label>Arrangement fee / treatment</label><strong>${$('loanFeeUnit').value==='percent'?num('loanFee')+'% = ':''}${money(loanResult.fees)} / ${$('loanFeeTreatment').options[$('loanFeeTreatment').selectedIndex].text}</strong></div><div class="box"><label>Interest basis</label><strong>${loanResult.interestBasis}</strong></div><div class="box"><label>Net advance</label><strong>${money(loanResult.netAdvance)}</strong></div><div class="box"><label>Total cost including fee</label><strong>${money(loanResult.totalCost)}</strong></div></div><div class="results"><div class="box"><label>Indicative repayment</label><strong>${repayment}</strong></div><div class="box"><label>Total interest</label><strong>${totalInterest}</strong></div><div class="box"><label>Total payable including fee</label><strong>${total}</strong></div></div><h2>Amortisation Schedule</h2><table><thead><tr><th>Period</th><th>Opening balance</th><th>Repayment</th><th>Interest</th><th>Capital</th><th>Closing balance</th></tr></thead><tbody>${table}</tbody></table><div class="disclaimer"><strong>Important:</strong> This document provides an illustrative calculation only and is not a finance offer, quotation or recommendation. Includes the entered arrangement fee. Other unentered fees and transaction costs are excluded. Actual repayments, interest calculations, fees, security requirements and facility terms vary by lender and product. Finance is subject to status, eligibility and lender approval.</div><div class="footer">Anytime Business Finance Ltd · Commercial finance intermediary, not a lender.</div><script>window.onload=()=>setTimeout(()=>window.print(),250)<\/script></body></html>`);
 w.document.close();
}

$('exportPdf')?.addEventListener('click',pdfIllustration);
$('exportSchedule')?.addEventListener('click',()=>{const head=['Period','Opening Balance','Repayment','Interest','Capital','Closing Balance'];const assumptions=[['Loan amount',loanResult.principal],['Rate type',loanResult.mode],['Rate value',num('loanRate')],['Arrangement fee unit',$('loanFeeUnit').value],['Arrangement fee entered',num('loanFee')],['Arrangement fee GBP',loanResult.fees],['Fee treatment',$('loanFeeTreatment').value],['Interest basis',loanResult.interestBasis],['Net advance',loanResult.netAdvance],['Total payable including fee',loanResult.totalRepayable],['Total cost',loanResult.totalCost],[]];const csv=[...assumptions,head,...rows.map(r=>r.map((v,i)=>i?v.toFixed(2):v))].map(r=>r.join(',')).join('\n');const blob=new Blob([csv],{type:'text/csv'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='ABF-amortisation-schedule.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)});
loan();io();dscr();asset();
})();
