(()=>{
const $=id=>document.getElementById(id), money=n=>new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP',minimumFractionDigits:2,maximumFractionDigits:2}).format(Number.isFinite(n)?n:0), num=id=>Number($(id)?.value)||0;
document.querySelectorAll('.calc-tab').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.calc-tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.calc-panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('calc-'+b.dataset.target).classList.add('active')}));
let rows=[];
function loan(){
 const P=Math.max(0,num('loanAmount')), annual=Math.max(0,num('loanRate'))/100, rawMonths=Math.max(1,Math.round(num('loanTerm'))), freq=Number($('loanFrequency').value), months=freq===4?Math.max(3,Math.round(rawMonths/3)*3):rawMonths, periods=freq===4?months/3:months, r=annual/freq; if(freq===4 && rawMonths!==months){$('loanTerm').value=months;}
 const pay=r===0?P/periods:P*r/(1-Math.pow(1+r,-periods)); let bal=P,totalInt=0; rows=[];
 for(let i=1;i<=periods;i++){const open=bal,int=open*r,capital=Math.min(pay-int,open),actual=capital+int;bal=Math.max(0,open-capital);totalInt+=int;rows.push([i,open,actual,int,capital,bal]);}
 $('loanPayment').textContent=money(pay);$('loanInterest').textContent=money(totalInt);$('loanTotal').textContent=money(P+totalInt);
 $('scheduleBody').innerHTML=rows.map(r=>'<tr>'+r.map((v,i)=>'<td>'+(i?money(v):v)+'</td>').join('')+'</tr>').join('');
}
function io(){const p=Math.max(0,num('ioAmount')),rate=Math.max(0,num('ioRate'))/100,m=Math.max(1,Math.round(num('ioTerm'))),monthlyRate=rate/12,type=$('ioType').value;let monthly=p*monthlyRate,interest,total;if(type==='compound'){total=p*Math.pow(1+monthlyRate,m);interest=total-p;$('ioMonthlyLabel').textContent='Month 1 interest';$('ioTotalLabel').textContent='Balance at maturity';$('ioNote').textContent='Rolled-up illustration assumes interest compounds monthly at the entered nominal annual rate ÷ 12, with no interim payments.';}else{interest=monthly*m;total=p+interest;$('ioMonthlyLabel').textContent='Monthly interest';$('ioTotalLabel').textContent=type==='serviced'?'Total paid over term incl. capital':'Amount due at maturity';$('ioNote').textContent=type==='serviced'?'Simple-interest illustration: interest is serviced monthly and the original capital remains due at maturity.':'Simple retained-interest illustration: no compounding is assumed; capital plus retained interest is due at maturity.';}$('ioMonthly').textContent=money(monthly);$('ioInterest').textContent=money(interest);$('ioCapital').textContent=money(p);$('ioTotal').textContent=money(total)}
function dscr(){const cash=num('dscrEbitda')+num('dscrAdjust'),debt=Math.max(0,num('dscrExisting'))+Math.max(0,num('dscrProposed'));$('dscrCash').textContent=money(cash);$('dscrDebt').textContent=money(debt);$('dscrRatio').textContent=debt>0?(cash/debt).toFixed(2)+'x':'—'}
function asset(){const cost=Math.max(0,num('assetCost')),dep=Math.min(cost,Math.max(0,num('assetDeposit'))),P=cost-dep,balloon=Math.min(P,Math.max(0,num('assetBalloon'))),n=Math.max(1,Math.round(num('assetTerm'))),r=Math.max(0,num('assetRate'))/100/12;let pay;if(r===0)pay=(P-balloon)/n;else pay=(P-balloon/Math.pow(1+r,n))*r/(1-Math.pow(1+r,-n));const totalPayments=pay*n+balloon,interest=totalPayments-P;$('assetFinanced').textContent=money(P);$('assetPayment').textContent=money(pay);$('assetInterest').textContent=money(interest);$('assetTotal').textContent=money(dep+totalPayments)}
[['loanAmount',loan],['loanRate',loan],['loanTerm',loan],['loanFrequency',loan],['ioAmount',io],['ioRate',io],['ioTerm',io],['ioType',io],['dscrEbitda',dscr],['dscrAdjust',dscr],['dscrExisting',dscr],['dscrProposed',dscr],['assetCost',asset],['assetDeposit',asset],['assetRate',asset],['assetTerm',asset],['assetBalloon',asset]].forEach(([id,fn])=>$(id)?.addEventListener('input',fn));

function pdfIllustration(){
 if(!rows.length)return;
 const amount=Math.max(0,num('loanAmount')), rate=Math.max(0,num('loanRate')), months=Math.max(1,Math.round(num('loanTerm'))), frequency=$('loanFrequency').options[$('loanFrequency').selectedIndex].text;
 const repayment=$('loanPayment').textContent,totalInterest=$('loanInterest').textContent,total=$('loanTotal').textContent,date=new Intl.DateTimeFormat('en-GB',{day:'2-digit',month:'long',year:'numeric'}).format(new Date());
 const table=rows.map(r=>'<tr>'+r.map((v,i)=>'<td>'+(i?v.toLocaleString('en-GB',{style:'currency',currency:'GBP'}):v)+'</td>').join('')+'</tr>').join('');
 const w=window.open('','_blank');
 if(!w){alert('Please allow pop-ups to create the PDF illustration.');return}
 w.document.write(`<!doctype html><html><head><title>ABF Finance Illustration</title><style>
 @page{size:A4;margin:15mm 14mm 17mm}*{box-sizing:border-box}body{font-family:Arial,sans-serif;color:#0B1F3B;margin:0;font-size:10px}.brand{border-bottom:3px solid #C9A96E;padding:0 0 14px;margin-bottom:22px;display:flex;justify-content:space-between;align-items:flex-end}.logo{font-family:Georgia,serif;font-size:23px;font-weight:bold;letter-spacing:.04em}.logo span{display:block;color:#C9A96E;font:700 7px Arial,sans-serif;letter-spacing:.22em;margin-top:5px}.date{color:#687386;font-size:9px}.title{font-family:Georgia,serif;font-size:25px;margin:0 0 7px}.intro{color:#687386;font-size:10px;margin-bottom:20px}.inputs,.results{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin-bottom:18px}.box{border:1px solid #d9dde3;padding:10px}.box label{display:block;color:#687386;font-size:8px;text-transform:uppercase;letter-spacing:.06em;margin-bottom:5px}.box strong{font-size:12px}.results .box{background:#0B1F3B;color:#fff;border-color:#0B1F3B}.results .box label{color:#dbe4ef}.results .box strong{color:#fff}.results{grid-template-columns:repeat(3,1fr)}h2{font-family:Georgia,serif;font-size:16px;margin:20px 0 9px}table{width:100%;border-collapse:collapse;font-size:8px}thead{display:table-header-group}th{background:#0B1F3B;color:white;padding:6px;text-align:right}th:first-child,td:first-child{text-align:center}td{padding:5px 6px;border-bottom:1px solid #e3e6ea;text-align:right}tr{page-break-inside:avoid}.disclaimer{margin-top:16px;padding-top:10px;border-top:1px solid #C9A96E;color:#687386;font-size:7.5px;line-height:1.45}.footer{margin-top:8px;font-size:7px;color:#8992a0;text-align:center}@media print{button{display:none}}
 </style></head><body><div class="brand"><div class="logo">ANYTIME BUSINESS FINANCE<span>EXPERIENCE. ACCESS. RESULTS.</span></div><div class="date">Finance Illustration · ${date}</div></div><h1 class="title">Loan Repayment & Amortisation Illustration</h1><p class="intro">Illustrative repayment schedule generated using the assumptions below.</p><div class="inputs"><div class="box"><label>Loan amount</label><strong>${money(amount)}</strong></div><div class="box"><label>Annual rate</label><strong>${rate.toFixed(2)}%</strong></div><div class="box"><label>Term</label><strong>${months} months</strong></div><div class="box"><label>Frequency</label><strong>${frequency}</strong></div></div><div class="results"><div class="box"><label>Indicative repayment</label><strong>${repayment}</strong></div><div class="box"><label>Total interest</label><strong>${totalInterest}</strong></div><div class="box"><label>Total repayment</label><strong>${total}</strong></div></div><h2>Amortisation Schedule</h2><table><thead><tr><th>Period</th><th>Opening balance</th><th>Repayment</th><th>Interest</th><th>Capital</th><th>Closing balance</th></tr></thead><tbody>${table}</tbody></table><div class="disclaimer"><strong>Important:</strong> This document provides an illustrative calculation only and is not a finance offer, quotation or recommendation. It does not include lender fees or other transaction costs unless expressly stated. Actual repayments, interest calculations, fees, security requirements and facility terms vary by lender and product. Finance is subject to status, eligibility and lender approval.</div><div class="footer">Anytime Business Finance Ltd · Commercial finance intermediary, not a lender.</div><script>window.onload=()=>setTimeout(()=>window.print(),250)<\/script></body></html>`);
 w.document.close();
}

$('exportPdf')?.addEventListener('click',pdfIllustration);
$('exportSchedule')?.addEventListener('click',()=>{const head=['Period','Opening Balance','Repayment','Interest','Capital','Closing Balance'];const csv=[head,...rows.map(r=>r.map((v,i)=>i?v.toFixed(2):v))].map(r=>r.join(',')).join('\n');const blob=new Blob([csv],{type:'text/csv'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='ABF-amortisation-schedule.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)});
loan();io();dscr();asset();
})();